<?php
include '../koneksi.php';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Pembelian</title>
    <link rel="stylesheet" href="admin/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="admin/assets/css/custom.css"> <!-- Sesuaikan dengan CSS kustom jika ada -->
</head>
<body class="has-navbar-vertical-aside navbar-vertical-aside-show-xl footer-offset">

<div class="content container-fluid">
    <div class="row align-items-center mb-3">
        <div class="col-sm mb-2 mb-sm-0">
            <h1 class="page-header-title">Detail Pembelian</h1>
        </div>
    </div>

    <?php
    // Cek apakah id_pembelian ada di URL
    if (!isset($_GET['id']) || empty($_GET['id'])) {
        die("ID pembelian tidak ditemukan!");
    }

    // Ambil detail pembelian berdasarkan id_pembelian dari URL
    $id_pembelian = $_GET['id'];
    $ambil = $koneksi->query("SELECT * FROM pembelian JOIN pelanggan ON pembelian.id_pelanggan = pelanggan.id_pelanggan WHERE pembelian.id_pembelian = '$id_pembelian'");

    if (!$ambil) {
        die("Query gagal: " . $koneksi->error);
    }

    $detail = $ambil->fetch_assoc();

    if (!$detail) {
        die("Detail pembelian tidak ditemukan untuk ID: $id_pembelian");
    }
    ?>

    <div class="card mb-4">
        <div class="card-body">
            <h5 class="card-title"><?php echo htmlspecialchars($detail['nama_pelanggan']); ?></h5>
            <p class="card-text">
                Telepon: <?php echo htmlspecialchars($detail['telepon_pelanggan']); ?> <br>
                Email: <?php echo htmlspecialchars($detail['email_pelanggan']); ?> <br>
                Tanggal Pembelian: <?php echo htmlspecialchars($detail['tanggal_pembelian']); ?> <br>
                Total Pembelian: Rp. <?php echo number_format($detail['total_pembelian']); ?>
            </p>
        </div>
    </div>

    <div class="card">
        <div class="card-header card-header-content-md-between">
            <div class="mb-2 mb-md-0">
                <form>
                    <div class="input-group input-group-merge input-group-flush">
                        <div class="input-group-prepend input-group-text">
                            <i class="bi-search"></i>
                        </div>
                        <input id="datatableSearch" type="search" class="form-control" placeholder="Search products" aria-label="Search products">
                    </div>
                </form>
            </div>
        </div>

        <div class="table-responsive datatable-custom">
            <table id="datatable" class="table table-borderless table-thead-bordered table-nowrap table-align-middle card-table">
                <thead class="thead-light">
                    <tr>
                        <th>No</th>
                        <th>Nama Produk</th>
                        <th>Harga</th>
                        <th>Jumlah</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $ambil = $koneksi->query("SELECT * FROM pembelian_produk JOIN produk ON pembelian_produk.id_produk = produk.id_produk WHERE pembelian_produk.id_pembelian = '$id_pembelian'");
                    if (!$ambil) {
                        die("Query produk gagal: " . $koneksi->error);
                    }
                    $nomor = 1;
                    while ($pecah = $ambil->fetch_assoc()) {
                    ?>
                    <tr>
                        <td><?php echo $nomor; ?></td>
                        <td><?php echo htmlspecialchars($pecah['nama_produk']); ?></td>
                        <td>Rp. <?php echo number_format($pecah['harga_produk']); ?></td>
                        <td><?php echo htmlspecialchars($pecah['jumlah']); ?></td>
                        <td>Rp. <?php echo number_format($pecah['harga_produk'] * $pecah['jumlah']); ?></td>
                    </tr>
                    <?php $nomor++; ?>
                    <?php } ?>
                </tbody>
            </table>
            <!-- Pagination controls -->
            <nav aria-label="Page navigation">
                <ul id="pagination" class="pagination justify-content-center">
                    <!-- Pagination items will be generated by JavaScript -->
                </ul>
            </nav>
            <div class="dataTables_info" id="datatable_info" role="status" aria-live="polite">Showing 1 to 10 of <?php echo $nomor - 1; ?> entries</div>
        </div>
    </div>
</div>

<script src="admin/assets/js/bootstrap.bundle.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const rowsPerPage = 10;
        const rows = document.querySelectorAll('#datatable tbody tr');
        const pagination = document.getElementById('pagination');
        const info = document.getElementById('datatable_info');
        let currentPage = 1;

        function displayPage(page) {
            const start = (page - 1) * rowsPerPage;
            const end = start + rowsPerPage;

            rows.forEach((row, index) => {
                row.style.display = index >= start && index < end ? '' : 'none';
            });

            info.textContent = `Showing ${start + 1} to ${Math.min(end, rows.length)} of ${rows.length} entries`;
        }

        function setupPagination() {
            const pageCount = Math.ceil(rows.length / rowsPerPage);
            pagination.innerHTML = '';

            for (let i = 1; i <= pageCount; i++) {
                const li = document.createElement('li');
                li.className = 'page-item';
                li.innerHTML = `<a class="page-link" href="#">${i}</a>`;
                li.addEventListener('click', function (e) {
                    e.preventDefault();
                    currentPage = i;
                    displayPage(currentPage);
                    document.querySelectorAll('.page-item').forEach(item => item.classList.remove('active'));
                    li.classList.add('active');
                });
                pagination.appendChild(li);
            }

            // Set the first page as active
            pagination.querySelector('li').classList.add('active');
        }

        function searchRows() {
            const searchInput = document.getElementById('datatableSearch').value.toLowerCase();
            const filteredRows = Array.from(rows).filter(row => {
                const textContent = row.textContent.toLowerCase();
                return textContent.includes(searchInput);
            });

            rows.forEach(row => row.style.display = 'none');
            filteredRows.forEach((row, index) => {
                row.style.display = index < rowsPerPage ? '' : 'none';
            });

            setupPagination(filteredRows.length);
            displayPage(1);
        }

        document.getElementById('datatableSearch').addEventListener('input', searchRows);

        setupPagination(rows.length);
        displayPage(currentPage);
    });
</script>

</body>
</html>
